server:
  port: 8082

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lex?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shop.schoolshop
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true





